{
 "title": "Http_Cpu",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Node Host Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Network Network Transmit Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum by(job) (node_network_transmit_bytes_total{instance=\"node-exporter:9100\"})"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "KB/s" } },
   "targets": [
    {
     "expr": "node_disk_io_now{instance=\"node-exporter:9100\"}"
    }
   ]
  },
  {
   "title": "Total Node Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (node_memory_MemTotal_bytes{instance=\"node-exporter:9100\"})"
    }
   ]
  },
  {
   "title": "Node CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(mode) (rate(node_cpu_seconds_total{instance=\"node-exporter:9100\"}[$__rate_interval]))"
    }
   ]
  },
  { "title": "Demo HTTP Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Top-3 rates",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(3, sum by(path, method) (rate(demo_api_request_duration_seconds_count[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95th percentile request latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, path, method) (rate(demo_api_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "{{path}} - {{method}}"
    }
   ]
  },
  { "title": "Demo CPU Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Instance CPU Usage ",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(demo_cpu_usage_seconds_total{mode!=\"idle\"}[5m])) / on(instance) group_left() demo_num_cpus",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}